spring.application.name=bizsquare-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/bizsquare_db
spring.datasource.username=postgres
spring.datasource.password=Syedimmu&97
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jooq.sql-dialect=Postgres

server.port=8080

# Replace with a strong, randomly generated secret key
application.security.jwt.secret-key=91826814490348
